### ISSUE TITLE
StrictMode error 

### ISSUE THREAD

**Issue by michiyosony** [doorbell/android-sdk#11]
When including these sdk files in a project (as opposed to adding the gradle dependency `compile 'io.doorbell:android-sdk:0.2.6@aar'`), calling the `show()` method produces a StrictMode violation for an unclosed resource.

For example, the line

```
 new Doorbell(MainActivity.this, <id>, <key>).show();
```

continuing to interact with the app causes the following error in the logs:

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'close' not called
         at dalvik.system.CloseGuard.open(CloseGuard.java:180)
         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:288)
         at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:406)
         at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
         at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
         at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
         at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
         at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
         at test.com.doorbelltest.RestRequest.executeRequest(RestRequest.java:256)
         at test.com.doorbelltest.RestRequest.access$100(RestRequest.java:66)
         at test.com.doorbelltest.RestRequest$ExecuteAsyncRequest.doInBackground(RestRequest.java:295)
         at test.com.doorbelltest.RestRequest$ExecuteAsyncRequest.doInBackground(RestRequest.java:291)
         at android.os.AsyncTask$2.call(AsyncTask.java:295)
         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
         at java.lang.Thread.run(Thread.java:818)
```

**Comment by manavo** [comment]
Thanks for reporting @michiyosony, will look into this! It'll probably need fixing here: https://github.com/manavo/Android-RESTapi

Planning on also switching to a different HTTP library (http://square.github.io/okhttp/ most likely), so now might be a good time!
